### ISSUE TITLE
Forcing Client Name in config

### ISSUE THREAD

**Issue by patschi** [nextdns/nextdns#192]
I have multiple devices using NextDNS using the client. While it does have the great functionality of reporting ClientInfo for the analytics, I'd rather like to be able to force a specific client name to identify a specific NextDNS service instance in the analytics - instead of every single device.

This allows having a high-level understanding/analytics, but it's not as granular as per each device. Specially when using DNS53, where no ClientInfo is available.

**Comment by rs** [comment]
This is a planned feature in the UI. Closing this issue as it is not linked to the CLI.

**Comment by patschi** [comment]
To be honest I'm not sure why this is being closed. I was indeed referring to the CLI version, not to the GUI-one.

**Comment by rs** [comment]
Maybe I did not fully understand your request. Can you please give an example?

**Comment by patschi** [comment]
Yeah, sure!

Simply said: I'd like to set a device name  within `nextdns.conf` which is being used to perform DNS lookups to NextDNS in the end. So I don't want to use the `report-client-info` , but still being able to manually set the devicename which is being used.

My goal: I have two DNS servers on one location, where I'm running NextDNS CLI client on. I don't want to make them reporting using the local unique hostnames of the individual DNS server. I'd like to set a manual name based on the location rather on the unique hostnames.

I hope this makes a bit more sense.

As far as I'm able to understand, following might need a small adjustment to make above possible:
https://github.com/nextdns/nextdns/blob/3ba0fa89a8cbca289853520ae93492f18c099124/run.go#L288-L293

Something like: (see it as pseudo-code)
```go
	if c.ReportClientInfo {
		// Only enable discovery if configured to listen to requests outside
		// the local host.
		enableDiscovery := !localhostMode
		setupClientReporting(p, &c.Conf, enableDiscovery)

	} else if (c.DeviceName != nil) {
		p.resolver.DOH.ClientInfo = func(q query.Query) (ci resolver.ClientInfo) {
			ci.Name = c.DeviceName
			return
		}
	}
```

**Comment by rs** [comment]
Oh ok got it. It’s not something we might add until there is more demands for it (you are the first), as we generally want to keep things as simple as possible. You should be able to hack it yourself without too much effort tho.

**Comment by patschi** [comment]
Yeah, sure. But to be honest I'm not really up to maintain a sort-of-NextDNS fork forever to have that functionality, so it might be really handy to have that functionality upstream. So overall the setting is also quite simple: When `report-client-info` is disabled, it allows you to use a custom `deviceName` in the config.

I also really like simplicity, that's why I'm looking forward using the NextDNS CLI client instead of any bigger dnscrypt/dohproxy-thingy out there to realize that.

I don't mind throwing my (probably outdated) GoLand on and to file a PR when it's tested and working.

**Comment by patschi** [comment]
Just to add: My thought on this is that this allows users to define how to collect/group DNS analytics based on their own decision. So this is a choice between reporting client information (basically full-in) and having no grouping at all.

**Comment by rs** [comment]
If we would support it, we would add a proper support with a “router” type of device in the analytics etc.

Reporting a fake device when client reporting is off is somewhat of a hack and might be seen as a bug by other users who DO NOT want to report any device identity. It can be simple in terms code but it adds a small hack that we will have to maintain over time.

If we start to accepting small hacks instead of either properly do it or not do it at all, we will — by experience — end up with a bloated product.

I hope you understand :)

**Comment by timkgh** [comment]
@rs could you reopen this issue please?
I'd like to see it implemented too. I have a few instances of nextdns client running and I want to identify each one rather than see them all as "Unidentified devices" in analytics.

**Comment by rs** [comment]
You can set custom names in /etc/hosts and `use-hosts` feature on.

**Comment by timkgh** [comment]
Not sure I understand how /etc/hosts helps. I want all requests from the nextdns cli itself to be identified in analytics, regardless of what clients actually use that nextdns cli instance. The nextdns cli needs to have a static identifier/name, e.g. "server1", "router2", etc.

**Comment by fouyos** [comment]
Just wanted a follow-up, the GUI version has this feature while the CLI?

**Comment by rs** [comment]
The GUI will use the hostname, same as for the CLI.

**Comment by timkgh** [comment]
The CLI does not report the hostname, the IP address of the host shows up in logs/analytics, not the hostname. This is with nextdns cli 1.8.8 running on Ubuntu 18.04.5 LTS.

**Comment by rs** [comment]
Did you turn on `report-client-info`?

**Comment by timkgh** [comment]
`report-client-info` is not what this issue is about. It's about reporting the **name** of the device where nextdns cli runs, not of the clients that connect to nextdns cli.
This reply explains it best:
https://github.com/nextdns/nextdns/issues/192#issuecomment-623161445

**Comment by rs** [comment]
`report-client-info` does both, just turn it on and it should just work.

**Comment by timkgh** [comment]
It does not work for me. If I turn it on, instead of reporting the IP of the host where nextdns cli runs it starts reporting the IPs of the clients that connect to nextdns cli with names that look like "Device #<hex>".
As the comment above that I pointed to explains, it's about grouping clients behind nextdns cli and protecting their privacy (IP, MAC, name, ...).

**Comment by crahan** [comment]
Adding a +1 to this request. I would like to be able to what @timkgh described.

Basically force a device name in the NextDNS app config that's running on the router.

**Comment by crahan** [comment]
@timkgh I'm not sure if you'll still read this given the latest update is from a while back, but after I removed the `addmac` option from `/etc/config/dhcp` I started to see the router's device name in my NextDNS logs instead of the randomly generated ID for the actual device that sits behind the router.

So, I now have NextDNS running on my Gl.Inet device. NextDNS listens on 127.0.0.1:5353 and dnsmasq is set up to forward any non-local requests to 127.0.0.1:5353. I did not add the `add-mac` or `add-subnet` options to the dnsmasq config via `/etc/config/dhcp` which appears to have done the trick.

Any DNS request that devices connected to the Gl.Inet router make will now show up with the hostname of the Gl.Inet router in the NextDNS logs. I hope this helps.
