### ISSUE TITLE
add reverse dns support for forwarder

### ISSUE THREAD

**Issue by marktroberts** [nextdns/nextdns#235]
forwarder in-addr.arpa.=10.10.10.16:753,10.10.10.15:753

Allow internal reverse lookups via forwarder config so internal systems can resolve hostnames.

Example: ELK resolving hosts for log data reports.

**Comment by dhoetger** [comment]
I'm not sure what version you were experiencing this on (helpful info for any future issues), but try updating to the latest version of nextdns (1.7.0 as of this comment) as this is working for me with the caveat that bogus-priv must also be set to true.

(The previous version I tested, 1.5.8, rejected configuring a forwarder for in-addr.arpa or for a specific reverse lookup zone like 168.192.in-addr.arpa.)

**Comment by marktroberts** [comment]
How do you configs differ from mine?

root@compungere:[/home/compunction]# nslookup 10.10.10.1
** server can't find 1.10.10.10.in-addr.arpa.: NXDOMAIN

root@compungere:[/home/compunction]# nextdns config
bogus-priv false
discovery-dns
hardened-privacy false
detect-captive-portals false
control /var/run/nextdns.sock
max-ttl 5s
log-queries true
report-client-info true
setup-router false
listen :53
config 10.10.10.0/27=<removed>
config 10.10.10.32/27=<removed>
config 10.10.10.64/27=<removed>
config 10.10.10.96/27=<removed>
config 10.10.10.128/27=<removed>
config 10.10.10.160/27=<removed>
config 10.10.10.192/26=<removed>
config <removed>
cache-max-age 1m0s
use-hosts true
timeout 5s
auto-activate false
forwarder compunction.net.=10.10.10.16:753,10.10.10.15:753
forwarder 10.10.10.in-addr.arpa.=10.10.10.16:753,10.10.10.15:753
cache-size 10MB
root@compungere:[/home/compunction]# nextdns version
nextdns version 1.7.0
root@compungere:[/home/compunction]#

**Comment by dhoetger** [comment]
I have `use-hosts` enabled but my hosts file is effectively empty. I also have `auto-activate` and `setup-router` enabled with no other cohabitated dns services. (My use case is purpose-built VMs to centralize workstation DNS requests with attribution, basically replacing TitanHQ's DNSTitan which cost more, did a bad job at this attribution piece, has [unresolved security vulnerabilities](https://twitter.com/danhoetger/status/1204141574621257728) and provided zero customer service.)
What's your use case that you have a bunch of devices with "non-real" hostnames discovered via mDNS? IoT or BYOD where you're "renaming" devices out of your control for ease of identification?

Since you have an authoritative zone file and a server hosting it, could you use `discovery-dns=<internaldnsserver>` to get those hosts named as you want? (Manual configuration of this attribute was just [introduced](https://github.com/nextdns/nextdns/commit/f8cc02f24d6e88396d107e372970f001e2f9f18c#diff-3baf47c64847a8fb8aaa8cc2e088513bR120) with 1.7.0.)

**Comment by marktroberts** [comment]
Yes, I am using NextDNS CLI on my linux DNS servers.  I use bind to define internal hostnames for server and workstations with forward and reverse zones.  My devices like iPhones have a default name of iPhone, so you have 15 of them on a subnet, its not helpful.

I just enabled discovery-dns in my config file, did not see any errors in the log file, so it appears to be working.  Will see on Monday if the logs are being populated with hostnames as I expect.
