### ISSUE TITLE
Unifi USG stops processing lookups periodically

### ISSUE THREAD

**Issue by ChrisColotti** [nextdns/nextdns#240]
was running 1.6.3 and an hour ago all things stopped working for lookups.  HAd to uninstall and re-install with 1.6.4 (also enabled the new caching options)

Is there a way to tell why the USG stops processing lookups?  Also just upgraded to the latest USG firmware this weekend as well.

**Comment by kunickiaj** [comment]
I've been experiencing this since even earlier versions and haven't figured out why. The only information i've been able to gather is that dnsmasq ends up with forked zombie processes when this happens. I've only experienced it when using the NextDNS CLI.

On 1.5.4 I was getting even several days before needing to restart dnsmasq. On 1.6.4 I've been experiencing it multiple times a day. Can confirm running `service dnsmasq restart` resolves the issue for me. Likewise so does `nextdns restart` but I think that's because it might trigger a dnsmasq restart as well.

example symptom:

```
dnsmasq   9449  0.0  0.0      0     0 ?        Z    20:51   0:00 [dnsmasq] <defunct>
dnsmasq   9450  0.0  0.0      0     0 ?        Z    20:51   0:00 [dnsmasq] <defunct>
1000     11120  0.0  0.1   2184   632 pts/0    S+   21:04   0:00 grep dnsmasq
dnsmasq  31966  0.0  0.4   6068  2188 ?        S    19:37   0:04 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service
```

There are also some reports of this symptom on the ubiquiti forums as well, so it's still unclear to me what the culprit is.

https://community.ui.com/questions/USG-dnsmasq-hung-requiring-restart/038ffa17-7b08-4fb5-bef7-bc6d507f1470

**Comment by kunickiaj** [comment]
More and more looking like a Ubiquiti issue: https://community.ui.com/releases/USG-Firmware-4-4-51/ba67ead1-4282-44c8-9a93-b34e9c24a835#comment/4aedf28e-4b54-4c38-a402-ccc7dea5ddce

**Comment by ChrisColotti** [comment]
Interesting that’s for commenting.  I’ll read the UBNT posts as well.  Appreciate it!

**Comment by ChrisColotti** [comment]
Update:  I will say after the initial update to 4.50, and the removal/re-install of the NDNS Client things have not stopped working.  While I am suspicious of the USG DNSMASQ updates I have not seen the issue again post update and full re-install of the client.  no idea....

**Comment by kunickiaj** [comment]
I’m on 4.44 and no issues. Seems like 4.51 is a bad update then. Wanna close out this issue?

**Comment by zcpnate** [comment]
I'm seeing this on 4.51 usg - behavior is that nextdns status reports "stopped" is there any way to turn on further nextdns logging?

**Comment by rs** [comment]
Are you on the last version of the CLI?

**Comment by zcpnate** [comment]
> Are you on the last version of the CLI?

yes am on v 1.9.4

**Comment by kunickiaj** [comment]
> I’m on 4.44 and no issues. Seems like 4.51 is a bad update then. Wanna close out this issue?

Just reiterating that the USG 4.51 update was all sort of trouble for me and downgrading solved my problems including with NextDNS. I don't think it's a NextDNS issue. Ubiquiti unfortunately has a terrible QA record.

**Comment by zcpnate** [comment]
Going to test a downgrade to 4.44 -- since switching from pi hole to nextdns/usg for dns, I've been experiencing random reboots with no logs as well.

We'll see how a downgrade goes.

**Comment by zcpnate** [comment]
Crashed again after the downgrade. I have rsyslog setup but nothing of note in any logs.

**Comment by vijvis** [comment]
Working fine on USG 3P version 4.4.51 with NextDNS version 1.9.4
