### ISSUE TITLE
EdgeOS NextDNS service died/killed after errors (also a question about multiple forwarders)

### ISSUE THREAD

**Issue by Sammy1Am** [nextdns/nextdns#277]
I've had this happen twice so far, the first about an hour after setting things up, and the second just now, ~26 hours later.

It seems to start with oodles (like dozens every second) of these errors:

> Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA unagi.amazon.com. (qry=34/res=12) 15866ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A unagi.amazon.com. (qry=34/res=12) 15866ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A connectivitycheck.gstatic.com. (qry=47/res=12) 15858ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A fcmconnection.googleapis.com. (qry=46/res=12) 15858ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A connectivitycheck.gstatic.com. (qry=47/res=12) 15858ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A smile.amazon.com. (qry=34/res=12) 24457ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA smile.amazon.com. (qry=34/res=12) 24457ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A api.box.com. (qry=29/res=12) 24457ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A connectivitycheck.gstatic.com. (qry=47/res=12) 24458ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A connectivitycheck.gstatic.com. (qry=47/res=12) 24458ms : doh resolve: context deadline exceeded
Jul 03 19:17:41 hostname nextdns[10843]: Query 127.0.0.1 UDP A pixel.advertising.com. (qry=39/res=12) 24458ms : doh resolve: context deadline exceeded

During which browsing starts to get slow (though doesn't seem to fail entirely).  The errors then start getting replaced with these:

> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP A unagi.amazon.com. (qry=34/res=12) 8657ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA unagi.amazon.com. (qry=34/res=12) 8657ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP A unagi.amazon.com. (qry=34/res=12) 8656ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA unagi.amazon.com. (qry=34/res=12) 8656ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP A connectivitycheck.gstatic.com. (qry=47/res=12) 8655ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP A smile.amazon.com. (qry=34/res=12) 8655ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA smile.amazon.com. (qry=34/res=12) 8654ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files
> Jul 03 19:17:47 hostname nextdns[10843]: Query 127.0.0.1 UDP AAAA d.joinhoney.com. (qry=33/res=12) 8654ms : doh resolve: dial tcp 1.1.1.1:443: socket: too many open files

And then finally the service goes down:

> Jul 03 19:19:25 hostname systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Jul 03 19:19:25 hostname systemd[1]: nextdns.service: Unit entered failed state.
Jul 03 19:19:25 hostname systemd[1]: nextdns.service: Failed with result 'signal'.

Starting the service again seems to resolve the problem.  I could add a restart clause to the systemd configuration to just restart it (and probably will long-term if there's not a resolution), but figure I'll just let it keep crashing for now to see if I can root out any problems.

Does anyone know what the `context deadline exceeded` and `too many open files` errors mean and are likely caused by?  

Also, I've added both 1.1.1.1 and 1.0.0.1 to my nextdns config like so: `forwarder https://1.1.1.1/dns-query,https://1.0.0.1/dns-query` but it seems like the errors I'm running into with 1.1.1.1 are preventing DNS lookups, so I assume nextdns isn't trying the second forwarder (or these errors somehow prevent it from doing so?).

**Context**
 - Version [e.g. 1.5.2]: 1.7.0
 - Platform [e.g. macOS, ASUS-Merlin]: EdgeOS 2.0.8 on EdgeRouter X SFP

**Comment by Sammy1Am** [comment]
A quick update:
The issue occurred again just now, so we made it ~51 hours this time (reasonably consistent Internet usage during that time, so I'm not sure it's like a memory leak/time thing).  I did notice earlier today though that there was a bit of a `context deadline exceeded` storm that lasted for a while, but never quite brought the service down.

It seems like maybe the nextdns service dies if it's dealing with too many of those errors (though I still don't know what that error means).

**Comment by rs** [comment]
Looks like a file handler leak. Needs investigation.

**Comment by Sammy1Am** [comment]
Also noticed this time that just before the service died my router's CPU was at 99% and it was nearly out of memory (probably not surprising new data points, but figured I'd share).

Is there any additional information I can gather/provide that might help resolving this issue, or should I go ahead and just put a periodic restart in systemd?

**Comment by rs** [comment]
If you are able to run a lsof on the pid of nextdns it would be helpful. A `nextdns trace` too.

**Comment by Sammy1Am** [comment]
Trace and lsof attached (my ip address replaced with `<myip>` but it was the external-facing IP from my router).  The trace doesn't make a lot of sense (since I haven't really dug into the code yet), but the lsof does seem a little over-long.

[ndns-trace.log](https://github.com/nextdns/nextdns/files/4889190/ndns-trace.log)
[ndns-lsof.log](https://github.com/nextdns/nextdns/files/4889191/ndns-lsof.log)

**Comment by rs** [comment]
Looks like the cli is leaking file descriptors. Can you please show the content of your cli conf?

**Comment by Sammy1Am** [comment]
Sure:

> cache-size 0
setup-router false
forwarder https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
cache-max-age 0s
report-client-info false
discovery-dns
detect-captive-portals false
auto-activate false
log-queries false
control /var/run/nextdns.sock
max-ttl 0s
hardened-privacy false
bogus-priv true
use-hosts true
timeout 5s
listen 127.0.0.1:5353

**Comment by nwalke** [comment]
I believe I also am running in to this issue.  Is there anything debug wise I can provide to help as well?

**Comment by ralban** [comment]
I believe I am having this issue too. I'm running EdgeOS v1.10.11 on EdgeRouter X SFP with NextDNS 1.7.0

My first occurrence of the error was early this morning. System memory and resources appeared normal in the EdgeOS GUI.
I tries a "nextdns restart", which seem to restore functionality for a few moments, but my users/family quickly complained a few minutes later. I had to reboot the router before I could do much more troubleshooting or log gathering. The few logs I have do show some "socket: too many open files" messages.

I mention the following in-case it contributes to the conditions resulting in this crash:
I configured the EdgeRouter such that the only resolver for the system is the NextDNS CLI (127.0.01:53). Each of my subnets DHCP servers are configured with the EdgeRouter as the only DNS server. I have DNAT rules that redirect DNS queries from any clients that hardcode DNS53 to that subnet's local DNS server. I have an egress firewall rule on the WAN that drops DNS53 from any host that isn't the EdgeRouter (I'm also dropping DoT/853 except for a few Androids where I'm toying with PrivateDNS). The EdgeRouter clock is accurate, but the router is without DNS until the NextDNS CLI loads (I just added an IP for a NIST NTP, just in-case). I imagine the NextDNS CLI handles boot-strapping the DoH connection without relying on much else besides accurate time.

I'm happy to provide other diagnostics as requested and would be interested in other work-arounds (cron to restart nextdns) until the bug is squashed.

**Comment by Sammy1Am** [comment]
@ralban I've had some success adding/modifying the highlighted lines in `/etc/systemd/system/nextdns.service`:

> [Unit]
Description=NextDNS DNS53 to DoH proxy.
ConditionFileIsExecutable=/config/nextdns/nextdns
After=network.target
Before=nss-lookup.target
Wants=nss-lookup.target
> 
> [Service]
StartLimitInterval=5
StartLimitBurst=10
Environment=SERVICE_RUN_MODE=1
ExecStart=/config/nextdns/nextdns run
**RestartSec=5**
LimitMEMLOCK=infinity
**Restart=always
RuntimeMaxSec=23000**
> 
> [Install]
WantedBy=multi-user.target

The two `Restart*` lines will ensure that if the service dies (which mine does after a few too many socket errors), it will be restarted after 5 seconds.  In practice this seems to mean that there's about 30-120 seconds of downtime from the user perspective as DNS queries will start to slow and fail before the service fully dies, but that's quick enough that streaming shouldn't be interrupted and it beats having to manually restart.

The `RuntimeMaxSec` line will proactively shutdown the service every 6-7 hours or so, but `Restart=always` will start it up again.  My hope here is that if there's some sort of leak, proactively restarting the service will keep things cleaner and avoid the errors I'm seeing.  I'm not 100% sure how effective this is; it **seems** like it's helping because at first I was getting a crash about once every 24 hours, but now I don't think I've seen one for a few days-- on the other hand, because the service restarts when it crashes now, I might just not be noticing the crashes :P

**Comment by ralban** [comment]
Providing an update:
I have not had to restart the service in several days. However, I did change my settings and made a change in my LAN. I think this issue might be related to [https://github.com/nextdns/nextdns/issues/287](url)

I experienced this symptom during my migration to the NextDNS CLI client resolver on my EdgeRouter, I had configured my 2 PiHole servers to use the EdgeRouter as their upstream DNS resolver (and the EdgeRouter resolver in-turn uses NextDNS CLI local proxy as its system/upstream resolver) until all clients renewed with DHCP and received new DNS settings. The PiHoles were configured with conditional forwarding to lookup hostnames of IP's making requests. Reverse lookups began failing during this time (PiHole dashboards showed IP addresses instead of host names). I had created Forwarder entries in the NextDNS CLI config with the appropriate format (server=/sub.lan/x.x.x.x), but I was unable to resolve any local devices via ping or nslookup.

I modified my NextDNS CLI config to remove the Forwarder entries and toggled bogus-priv to false for now. I'm using Rewrites in the NextDNS UI to resolve common internal servers as a work-around. My NAS continues to make reverse-lookups and I can now see those requests in NextDNS logs. The PiHoles have been shutdown (huzzah!).

Current config is:

discovery-dns
detect-captive-portals false
hardened-privacy false
bogus-priv false
setup-router true
control /var/run/nextdns.sock
config ID-OF-MY-CONFIG
log-queries false
cache-size 10MB
cache-max-age 0s
timeout 5s
listen localhost:53
max-ttl 5s
report-client-info true
use-hosts true
auto-activate true

**Comment by Sammy1Am** [comment]
I suspect removing the `forwarder` entries is what did it, since it seems like the error stems from connections to the `forwarder` specified servers.  This does (maybe) seem to suggest that the connections made to NextDNS servers don't have the same leaking problem as connections to forwarders, but not sure if those are directly comparable.

Unfortunately since my end-goal is to use the `forwarder` setting, I'm still stuck on my end.

**Comment by ralban** [comment]
I'm not sure where I'll land on my need for forwarders in a post-pihole world. My use-case was resolving internal hosts for plex and internal admin consoles. It would seem NextDNS CLI could do this auto-magically since it is already discovering hostnames for logging.
________________________________

**Comment by Sammy1Am** [comment]
I don't want to get too off topic from the original issue, but my use case is basically the same.  Instead of relying on NextDNS to discover/resolve internal host names though, I'm letting the DHCP host on the EdgeRouter do that.  I have NextDNS CLI running on port 5353 (see configuration above), and I've configured the EdgeRouter's DNS to point to 127.0.0.1 (NextDNS CLI) for resolving.

That way internal hosts are returned by the EdgeRouter directly (without needing an additional discovery step), but NextDNS still handles all outgoing DNS.

**Comment by bdwilson** [comment]
FYI, I don't have forwarder entries and I'm running into the same issues with: context deadline exceeded - no errors about sockets, however after those deadline exceed entries, browsing gets slow.  

Unfortunately I'm still on v1.10.11, so I don't have the luxury of having access to systemd to do the restarts as @Sammy1Am suggested. I do have a cronjob that restarts nextdns DAILY at 4am. That has worked up until today when things got slow  around 3-4pm.  Symptoms were that things like my honeywell thermostat couldn't get to the cloud, Anveo SIP adapter went offline. I was not there, but I suspect nothing could resolve things.  Perhaps I need to look at @Sammy1Am's fix considering my daily restart was proven ineffective today.

Here is my config.   
```
cache-size 0
cache-max-age 0s
hardened-privacy false
timeout 5s
control /var/run/nextdns.sock
max-ttl 0s
report-client-info true
bogus-priv true
setup-router true
listen localhost:53
config a44d98
log-queries false
discovery-dns
detect-captive-portals false
use-hosts true
auto-activate true
```

**Comment by ralban** [comment]
Try setting: 
`bogus-priv false `
as a work-around. 
I still have yet to restart the device or service since changing that setting.

**Comment by bdwilson** [comment]
> Try setting: 
> 
> `bogus-priv false `
> 
> as a work-around. 
> 
> I still have yet to restart the device or service since changing that setting. 

That did not fix it for me. It just happened again, still with the 4am restart.
