### ISSUE TITLE
Respect forwarder order

### ISSUE THREAD

**Issue by timkgh** [nextdns/nextdns#305]
In the config file I set:
`forwarder https://dns.google/dns-query#8.8.8.8,https://dns.nextdns.io#45.90.28.0`

But all queries seem to go to NextDNS. I'd like the order to be respected so that Google is the main upstream server and only go to NextDNS if Google doesn't respond.

**Comment by rs** [comment]
Split them on two forwarder lines

**Comment by Fail-Safe** [comment]
Curious about your use-case here. Google DNS has pretty solid uptime, so I can't imagine you would hit a case where it wouldn't be available. Regardless, I think there's a few things going on with your current syntax.

To achieve what you've described, I believe you would add each of the forwarder URLs as separate forwarder entries. The first one declared should be the one used as "primary" in this case, but I'm not sure if the "fallback" to NextDNS scenario works or not.

It looks to me like everything beginning with the first hash symbol would be interpreted as a comment. I think you should try:
```
...
forwarder https://dns.google/dns-query
forwarder https://dns.nextdns.io
...
```

Give that a shot and see how it goes.

**Comment by timkgh** [comment]
`#` is not a comment in this context. It's the way to specify the IP address of the host in case you don't have an alternate DNS server already that can look it up.

**Comment by Fail-Safe** [comment]
> `#` is not a comment in this context. It's called a URI fragment. It's the way to specify the IP address of the host in case you don't have an alternate DNS server already that can look it up.

I'm familiar with a URI fragment (bootstrap IP), but didn't recall if @rs had implemented its support in the code. I do see it is referenced [here](https://github.com/nextdns/nextdns/blame/master/config/config.go#L103), so it does appear your config would have worked in theory. Apologies for my misinformed statements in my previous reply.

> As for Google being reliable, yes, true, but the network between me and Google may not be, routers along the way can have issues, while routes to NextDNS servers may work just fine.

I hear where you are coming from, again, in theory. But Google DNS is anycast, as is NextDNS. As a result, both should be quite capable of sustaining an upstream routing issue given built-in failover mechanisms within the foundation of anycast. The main exception that comes to mind is if you have a last-mile routing issue. In that case, your internet connection is likely down anyway and DNS is one of many casualties there.

Regardless, sounds like you and @rs have covered all the bases. Hope you are able to get a workable solution figured out for your use-case. 👍

**Comment by yrro** [comment]
I have a use case this. It's pretty niche, but since you asked... ;)

I have a domain, `my.example.com` that has authoritative DNS servers on the internet, and also on my local network.

On my local network I use `nextdns` to provide recursive DNS services. I run `nextdns -forwarder my.example.com=192.2.0.53` so that requests for `my.example.com` always go to the authoritative DNS server on my local network.

As a result, if the server on my local network is down, then `my.example.com` is not resolvable.

What I'd like is for `nextdns` to fall back to the public servers if the server on my local network is down. Something like `-resolver my.example.com=192.2.0.53>198.51.100.53,203.0.113.53`. That ugly-looking syntax expresses the preference to forward queries to 198.51.100.53 at first, and then, with equal preference, `198.51.100.53` and `203.0.113.53`.

As for why this is actually useful: the DNS service has the concept of 'locations', and is able to modify its responses in order to direct clients to prefer to talk to servers within their own location.

For instance, the server on my local network is `ipa2-oxf.my.example.com`, in the `oxf` location. With `nextdns` forwarding queries for `my.example.com` towards `ipa2-oxf.my.example.com`, clients in `oxf` see:

```
$ dig +short -t srv _ldap._tcp.my.example.com
_ldap._tcp.oxf._locations.my.example.com
50 100 389 ipa0.my.example.com.
50 100 389 ipa1.my.example.com.
0 100 389 ipa2-oxf.my.example.com.
```

As a result, they will prefer to talk to `ipa2-oxf.my.example.com` since it has a lower priority value. It's pretty neat, but in the event of `ipa2-oxf.my.example.com` being down, clients within `oxf` won't be able to resolve anything within `my.example.com`.
