### ISSUE TITLE
NextDNS not activating on Fedora 33

### ISSUE THREAD

**Issue by evanleck** [nextdns/nextdns#349]
I've run the automatic install and see the systemd service running but visiting my.nextdns.io says that I'm not configured to use NextDNS. My `/etc/resolv.conf` has the following:

```
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

options edns0 trust-ad
nameserver 127.0.0.1
```

I wonder if this is because of the change to [use systemd-resolved](https://fedoraproject.org/wiki/Releases/33/ChangeSet#systemd-resolved) (more [details here](https://fedoraproject.org/wiki/Changes/systemd-resolved))? I'm not familiar with how this stuff works or I'd try to help out more, sorry :/ 

I'm running nextdns 1.8.6 on Fedora 33 with kernel 5.8.15

**Comment by ankworld** [comment]
I found workaroud.

Because systemd-resolve is disable DNSoverTls by default. Enable DNSOverTLS to make it work.

edit /etc/systemd/resolved.conf

uncomment **DNSOverTLS=no** and change to **DNSOverTLS=yes**

`sudo systemctl restart systemd-resolved.service`

**Comment by captainwarptime** [comment]
I seem to have the exact same issue. NextDNS CLI installs and runs properly, and successfully takes command of /etc/resolv.conf. Yet, the system is still using the default resolvers of whatever network it's connected to. I have removed and re-installed it several times, to no effect. The "nextdns log" command returns no error, e.g.:

```
-- Logs begin at Sun 2020-12-13 20:04:43 CET, end at Mon 2020-12-14 23:05:28 CET. --
déc 14 20:10:05 systemd[1]: Started NextDNS DNS53 to DoH proxy..
déc 14 20:10:05 nextdns[1562]: Starting NextDNS 1.9.4/linux on localhost:53
déc 14 20:10:05 nextdns[1562]: Listening on TCP/[::1]:53
déc 14 20:10:05 nextdns[1562]: Listening on UDP/127.0.0.1:53
déc 14 20:10:05 nextdns[1562]: Listening on UDP/[::1]:53
déc 14 20:10:05 nextdns[1562]: Listening on TCP/127.0.0.1:53
déc 14 20:10:10 nextdns[1562]: Activating
déc 14 20:10:15 nextdns[1562]: Network change detected: virbr0 added
déc 14 20:10:15 nextdns[1562]: Connected 178.255.153.47:443 (con=16ms tls=51ms, TLS13)
déc 14 20:10:15 nextdns[1562]: Switching endpoint: https://anexia-zrh-1.edge.nextdns.io#178.255.153.47,2a00:11c0:5:613::3
déc 14 20:12:02 nextdns[1562]: Connected 178.255.153.47:443 (con=17ms tls=25ms, TLS13)
déc 14 20:24:50 nextdns[1562]: Connected 178.255.153.47:443 (con=16ms tls=31ms, TLS13)
déc 14 22:50:36 nextdns[1562]: Connected 178.255.153.47:443 (con=17ms tls=21ms, TLS13)
```
**Context**

- Version = 1.9.4
- Platform = Linux, Fedora 33 (kernel 5.9.13 w/ default network configuration)

**Comment by evanleck** [comment]
For anyone else encountering this issue, @captainwarptime included, disabling `systemd-resolved` did the trick for me:

```sh
sudo systemctl disable systemd-resolved
```
It's not exactly a "fix" but it gets NextDNS working.

**Comment by drewr** [comment]
Unsure of what outright disabling systemd-resolved might break, I added the NextDNS config to `/etc/systemd/resolved.conf` per the setup instructions and that also works.

**Comment by evanleck** [comment]
@drewr can you link me to those instructions? What did you put in that config file?

**Comment by drewr** [comment]
It's in the list under the Linux tab at `https://my.nextdns.io/${CONFIG_ID}/setup`, which shows something similar to:

```
[Resolve]
DNS=45.90.28.0#${CONFIG_ID}.dns1.nextdns.io
DNS=2a07:a8c0::#${CONFIG_ID}.dns1.nextdns.io
DNS=45.90.30.0#${CONFIG_ID}.dns2.nextdns.io
DNS=2a07:a8c1::#${CONFIG_ID}.dns2.nextdns.io
DNSOverTLS=yes
```

**Comment by evanleck** [comment]
@drewr thanks, I didn't see that there!

For anyone running into this issue in the future, I would avoid installing the CLI if your system is using `systemd-resolved` for DNS resolution and instead refer to the setup section mentioned above.

In addition to the settings from the NextDNS website I had to add `Domains=~.` so that my wifi would use the global DNS settings instead of the per-link DHCP-provided DNS. Thanks to the ever excellent ArchWiki for [that trick](https://wiki.archlinux.org/index.php/Systemd-resolved#DNS). Altogether, my `/etc/systemd/resolved.conf` looks like this:

```
[Resolve]
DNS=45.90.28.0#${CONFIG_ID}.dns1.nextdns.io
DNS=2a07:a8c0::#${CONFIG_ID}.dns1.nextdns.io
DNS=45.90.30.0#${CONFIG_ID}.dns2.nextdns.io
DNS=2a07:a8c1::#${CONFIG_ID}.dns2.nextdns.io
DNSOverTLS=yes
Domains=~.
```

While this gets NextDNS working with `systemd-resolved` I'd still say that there's a bug because the CLI reports a successful activation even though it's not working.

FYI @captainwarptime

**Comment by mflannery** [comment]
At first, I installed the NextDNS client but it would not activate because systemd-resolved was already listening on port 53 (with a Vanilla install of Fedora 33 which was not set up to be a DNS server).  So I first stopped and disabled systemd-resolved:

sudo systemctl disable --now systemd-resolved.service

Then restart the nextdns service

sudo systemctl restart nextdns.service

That worked but my /etc/resolv.conf file was linked to a now non-existent file so anything that wanted to read /etc/resolv.conf couldn't.  I found [this](https://fedoraproject.org/wiki/Changes/systemd-resolved) website which provided some good documentation on systemd-resovled.  The most important item was that you can relink /etc/resolv.conf to an actual /etc/resolv.conf file, even with systemd-resolved disabled.  So I did that and restarted my nextdns client:

sudo ln -sfv /run/systemd/resolve/resolv.conf /etc/resolv.conf
sudo systemctl start nextdns.service

Now I have my /etc/resolv.conf file back and I have NextDNS running such that my fedora server is a DNS server for my entire network.  

To resolve hosts within my network. I added a forwarder setting to my nextdns config.  To see your config do:

sudo nextdns config

To add a forwarder:

sudo nextdns config set forwarder domain.com=192.168.1.1

where domain.com is your internal network domain and the ip address is to your internet router/dns server.  

Now I can resolve ip addresses outside my network via nextdns and inside my network via the nextdns client forwarding requests to my router.
