### ISSUE TITLE
Add fallback server for both iOS and Android apps

### ISSUE THREAD

**Issue by bigdargon** [nextdns/nextdns#427]
Hi team,

I am using pihole for home network, some devices have NextDNS app installed.  When I look at the pihole log, I see the query for domain ‘dns.nextdns.io’ frequently. Even devices running iOS 14 are the same.

What happens when certain wifi networks in which network operators block NextDNS domains?  So I suggest adding fallback server so as not to be blocked.  This is similar to the Bootstrap IPs of the Apple Configuration Profile.

Thanks!

**Comment by rs** [comment]
It’s already the case with cli, there are 3 modes of fallback. On iOS you have to check the bootstrap IP option manually but then you lose the ultra low latency steering.

**Comment by crssi** [comment]
What is `ultra low latency steering`?

Thank you and cheers

**Comment by rs** [comment]
Unlike anycast that uses BGP routing to steer you to the “closest” pop, ultra low latency steering uses  manual steering we developed, based on geo IP and reverse latency measurements. This steering work using DNS. The magic happens when you resolve dns.nextdns.io, we give you unicast IPs instead of the usual anycast ones.

With bootstrap IPs, you force anycast, so it inherently disables this feature.

**Comment by crssi** [comment]
Cool, thank you. ❤️ 

With `bootstrap IPs` you mean using `45.90.28.*` and `45.90.30.*`?

**Comment by rs** [comment]
Yes

**Comment by crssi** [comment]
Thank you. 😄 👍
