### ISSUE TITLE
Client hostnames not reported when forwarding to NextDNS from dnsmasq (on EdgeRouter)

### ISSUE THREAD

**Issue by bdwilson** [nextdns/nextdns#432]
I need resolution to flow through dnsmasq because I have local dns names that I need to resolve and have been unsuccessful in doing this without going through dnsmasq. I can't put the responses into NextDNS configuration as I only want the local IP's to resolve for hosts on my network. 

My hosts running NextDNS app show hostnames, but other devices on my network show up as Device #EF23xx. Reverting to a configuration that doesn't have dnsmasq as the middle man for resolutions shows correct device hostnames. 

If I use the configurations below, I get full client names in nextdns logs but no local dnsmasq DNS entries.  If I change ```setup-router false``` on NextDNS, then I get local DNS entries from dnsmasq but do not get full hostnames in nextdns logs. 

Here is my configuration for dnsmasq:

```
  forwarding {
     cache-size 1000
     listen-on eth1
     listen-on eth1.1003
     listen-on switch0
     listen-on vtun0
     listen-on eth1.1004
     listen-on wg0
     name-server 127.0.0.1
     options listen-address=192.168.1.1
     options strict-order
     options bogus-priv
     options server=127.0.0.1#5342
     options add-mac
     options add-subnet=32,128
 }

```
Here is my NextDNS configuration:

```
config a44d98
detect-captive-portals false
hardened-privacy false
use-hosts true
setup-router true
report-client-info true
discovery-dns
timeout 5s
auto-activate true
max-ttl 5s
bogus-priv false
listen 127.0.0.1:50053
listen 127.0.0.1:5342
control /var/run/nextdns.sock
log-queries false
cache-size 10MB
cache-max-age 0s
```

**Context**
 - Version: 1.10.1
 - Platform: EdgeRouter OS 1.10.10

**Comment by nick-rigby** [comment]
@bdwilson Whilst my setup is different (opnsense) to fix this I had to delete my DHCP static reservations and recreate.

**Comment by rs** [comment]
You need to put dnsmasq behind nextdns CLI and use a forwarder.

**Comment by bubbaiOS** [comment]
> You need to put dnsmasq behind nextdns CLI and use a forwarder.

Can you elaborate on this or point to documentation? I tried forwarding requests from dnsmasq to nextdns, but those didn't include the client info in nextdns logs.

**Comment by rs** [comment]
https://github.com/nextdns/nextdns/wiki/Split-Horizon

**Comment by bubbaiOS** [comment]
I've tried without success to get this to work.  I assume clients need to resolve against NextDNS cli DNS server and NextDNS will selectively forward requests matching my domain to my local dnsmasq server. But given the configuration below, this is not how it's working.  It appears to be client -> dnsmasq -> nextdns -> dnsmasq (if local domain is given).  

If setup-router=true, then it drops port=0 into the dnsmasq configuration, thus making it so I can't forward requests to dnsmasq via NextDNS. 

If setup-router=false and this configuration on EdgeRouter:
root@router# show service dns forwarding
 cache-size 1000
 listen-on eth1
 listen-on eth1.1003
 listen-on switch0
 listen-on vtun0
 listen-on eth1.1004
 listen-on wg0
 options listen-address=192.168.1.1
 options strict-order
 options bogus-priv
 options add-mac
 options add-subnet=32,128
 options server=127.0.0.1#50053

and NextDNS config:
  setup-router false
  detect-captive-portals false
  hardened-privacy false
  auto-activate true
  config xxxxxx
  max-ttl 5s
  timeout 5s
  cache-size 10MB
  cache-max-age 0s
  report-client-info true
  discovery-dns
  bogus-priv false
  use-hosts true
  listen 127.0.0.1:50053
  control /var/run/nextdns.sock
  log-queries false

DNS resolutions work and show local IP addresses, but client hostnames don't show up correctly in NextDNS logs.  If I add a conditional forward for my domain: forwarder mydomain.net=192.168.1.1, I can tell it's trying to forwarding it to that server, because it's hanging.

Hopefully I'm missing something simple.
Thanks!

**Comment by rs** [comment]
If dnsmasq is your dhcp, nextdns will read names in the dhcp lease so you don’t have to forward anything.

**Comment by bubbaiOS** [comment]
> If dnsmasq is your dhcp, nextdns will read names in the dhcp lease so you don’t have to forward anything.

It is my DHCP server. It's showing the external DNS entry and not the internal entry when NextDNS is setup with setup-router=true. The last configuration I have is close but the dns resolution is hanging.

**Comment by rs** [comment]
It should just work. Please check the content of the dhcp lease. If setup-router and report-client-info are on, you should at the very lease see individual clients with unique ids and their private ips in the logs. If you don’t, something is not properly setup.

**Comment by bubbaiOS** [comment]
> It should just work. Please check the content of the dhcp lease. If setup-router and report-client-info are on, you should at the very lease see individual clients with unique ids and their private ips in the logs. If you don’t, something is not properly setup.

It does report client info correctly when configured that way, but local DNS resolution doesn't work when configured.

**Comment by bubbaiOS** [comment]
For others having the same issue, here was my fix for EdgeRouter/EdgeOS.  I found this past issue that helped me [resolve it](https://github.com/nextdns/nextdns/issues/341#issuecomment-706738980).  You can choose something other than 777 - I was feeling lucky. 

1) Make sure your DHCP server(s) have a domain configured (yourdomain.net)
2) Configure dnsmasq this way. I have **no** `listen-address` or `name-server` options set for dns forwarding
```
 set service dns forwarding options strict-order
 set service dns forwarding options bogus-priv
 set service dns forwarding options port=777
 set service dns forwarding options server=127.0.0.1
```
3) Configure NextDNS this way.
```
forwarder yourdomain.net.=127.0.0.1:777
log-queries false
max-ttl 5s
setup-router false
cache-max-age 0s
report-client-info true
detect-captive-portals false
timeout 5s
auto-activate true
control /var/run/nextdns.sock
config xxxxx
bogus-priv false
listen 0.0.0.0:53
cache-size 10MB
discovery-dns 127.0.0.1:777
hardened-privacy false
use-hosts true
```
4) Restart dnsmasq `/etc/init.d/dnsmasq restart` restart nextdns `nextdns restart`

Keep in mind setting listen to 0.0.0.0:53 will listen on all interfaces, so you need to make sure you're not allowing access via your firewall configuration.

**Comment by hazarjast** [comment]
> For others having the same issue, here was my fix for EdgeRouter/EdgeOS. I found this past issue that helped me [resolve it](https://github.com/nextdns/nextdns/issues/341#issuecomment-706738980). You can choose something other than 777 - I was feeling lucky.
> 
> 1. Make sure your DHCP server(s) have a domain configured (yourdomain.net)
> 2. Configure dnsmasq this way. I have **no** `listen-address` or `name-server` options set for dns forwarding
> 
> ```
>  set service dns forwarding options strict-order
>  set service dns forwarding options bogus-priv
>  set service dns forwarding options port=777
>  set service dns forwarding options server=127.0.0.1
> ```
> 
> 1. Configure NextDNS this way.
> 
> ```
> forwarder yourdomain.net.=127.0.0.1:777
> log-queries false
> max-ttl 5s
> setup-router false
> cache-max-age 0s
> report-client-info true
> detect-captive-portals false
> timeout 5s
> auto-activate true
> control /var/run/nextdns.sock
> config xxxxx
> bogus-priv false
> listen 0.0.0.0:53
> cache-size 10MB
> discovery-dns 127.0.0.1:777
> hardened-privacy false
> use-hosts true
> ```
> 
> 1. Restart dnsmasq `/etc/init.d/dnsmasq restart` restart nextdns `nextdns restart`
> 
> Keep in mind setting listen to 0.0.0.0:53 will listen on all interfaces, so you need to make sure you're not allowing access via your firewall configuration.

Thank you for coming back to post this detailed reply. Your configuration details actually help me resolve two issues in my pfSense usage of NextDNS CLI. Firstly, I could never get dnsmasq ('DNS Forwarder') to play nice with NextDNS so I had disabled all DNS capability in pfSense which was a bummer since local LAN hostname resolution was lost. Secondly, I just updated to pfSense 2.5.2 recently and found that I could no longer view the 'DHCP Leases' page with NextDNS CLI as the only locally configured DNS server.

Applying your reference configurations for dnsmasq and NextDNS not only allowed me to have local LAN hostname resolution working again, but made it so I could view the 'DHCP Leases' page again! I still don't know the exact root causes in my earlier attempts to get dnsmasq and NextDNS to play nice, now things are working like a dream. Many thanks to you!

**Comment by bhusang** [comment]
@hazarjast   Your post is timely as I have the same setup (and problem). Was there anything special you did for dnsmasq in the pfSense GUI?

**Comment by hazarjast** [comment]
> @hazarjast Your post is timely as I have the same setup (and problem). Was there anything special you did for dnsmasq in the pfSense GUI other than what you outlined above?
> 
> (check) Enable DNS forwarder (check) Register DHCP leases ... (check) Register DHCP static ...
> 
> what about the remainder of the options? And in the Custom options box?

For DNS Query Forwarding I have "Query DNS servers sequentially" unchecked due to my DNS settings under "General Setup" (which I will reference below). I have "Require domain" checked so that NextDNS isn't spammed with any forwarding of LAN hosts for which FQDN is not specified. Also ahve "Do not forward private reverse lookups" much for the same reasons I have stated for "Require domain".

Since I am not using IPv6 at present in my setup I have "Interfaces" set to "Localhost" with "Strict interface binding" selected (you may not want this if you are running IPv6 or dual-stack).

Finally, under "System - General Setup - DNS Servers" I have put the IPs of my default NextDNS servers which is probably moot (just put those in place in case on reboot some queries are needed before NextDNS CLI daemon is running). The important setting here, that appears to make the DHCP "Leases" page load, is to set "DNS Resolution Behavior" to "Use local DNS (127.0.0.1), ignore remote DNS Servers".

Under my "DHCP Server" settings I have DNS server for clients set to the local LAN IP of pfSense so that all DNS requests are routed to NextDNS (which in turn sends local LAN host requests to dnsmasq). I have some screenshots in [this thread](https://forum.netgate.com/topic/161424/dhcp-lease-screen-not-loading/94) for reference.
