### ISSUE TITLE
Excessive CPU use NextDNS and DNSMasq integration

### ISSUE THREAD

**Issue by nick-rigby** [nextdns/nextdns#435]
Previously I've been running NextDNS behind DNSMasq but since changing NextDNS to sit in front of DNSMasq to allow for client names to be passed into the reporting the CPU usage for both has skyrocketed.
![image](https://user-images.githubusercontent.com/7390241/110602507-319a9500-81da-11eb-8eaa-d5842a15abe1.png)

Happy to provide any debug logs to help troubleshoot.

NextDNS = 1.11.0
DNSMasq =  2.84
OS = OPNsense 21.1.2-amd64

**Comment by nick-rigby** [comment]
> Did you run the same version before? What is the output of `nextdns config`?

Sure did, output of config below:

cache-size 10MB
cache-max-age 0s
max-ttl 5s
timeout 5s
control /var/run/nextdns.sock
detect-captive-portals false
setup-router false
auto-activate true
listen 0.0.0.0:53
discovery-dns 127.0.0.1:5342
bogus-priv true
config REDACTED
report-client-info true
hardened-privacy false
use-hosts true
root@edge:~ #

**Comment by rs** [comment]
Can you try without discovery-dns?

**Comment by nick-rigby** [comment]
@rs this removes the excessive CPU usage but I now the client name is no longer in the reporting interface and is back to _Device #xxxxx_

**Comment by timkgh** [comment]
I ran into this problem in the past too. The issue is that nextdns and dnsmasq get into this infinite loop where they forward requests back and forth to each other as fast as they can.
```
---> dnsmasq ------> nextdns -----> NextDNS upstream servers
        ^                      |
        |                      |
        -------- discovery -----
```
(this can happen if nextdns is in front also)

You have to break that loop. I have changed my setup so that dnsmasq serves DHCP and local DNS names only and **it has no upstream server configured**, all it can resolve is local names. nextdns cli is the main DNS server for public names. For my local domains I have nextdns configured to forward the requests to dnsmasq (using the `forwarder` and `discovery-dns` directives). Works well, no loops.
```
---> nextdns --- (discovery/local names) ---> dnsmasq  ---| (no upstream)
        |
        |------> NextDNS upstream servers
```

I think nextdns tries to prevent the loop but maybe it does not work in all cases.
