### ISSUE TITLE
Lastest release of cli has issues with local reverse lookups

### ISSUE THREAD

**Issue by hobybrenner** [nextdns/nextdns#487]
&lt;Describe the bug

I have nextdns cli setup on its own and have it forwarding local dns to a server running dnsmasq and everything is fine and dandy... reverse works, etc.  When updating to 1.32.1 it seems to break doing any local reverse lookups now.

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:

**Comment by chr-lei** [comment]
How are you doing your forwarding to the local dnsmasq server? discovery-dns or via forwarder... entries?

**Comment by dbeusink** [comment]
I've the exact same issue when using NextDNS CLI on EdgeOS (USG-3P v4.4.55). With the cache option off all Bonjour/dns-sd traffic (lb._dns-sd._udp.0.2.168.192.in-addr.arpa) will be sent to NextDNS (appears in my.nextdns.io) resulting in DNS timeouts. With the cache option on the queries are resolved. I think there is something wrong with the automatic router setup (resolv and/or dnsmasq). However using the cache option will result in kernel panics (something with kernel paging, I'm investigating this at the moment but limited the cache size to 1MB at the moment instead of 10MB).

**Comment by hobybrenner** [comment]
It looks like this still fails with the latest release.
