### ISSUE TITLE
UDM Pro installing with caching(DNS Masq disable)

### ISSUE THREAD

**Issue by linuxfrag** [nextdns/nextdns#488]
When I install NextDNS Cli with caching support eventually at some point my Layer 2 switch(Unifi Flex XG) will stop working on the network and continually try to readd the device. Right now I have NextDNS configured without caching so that DNS Masq is not disabled and my Layer 2 switch has been running without an issue. This is the only layer 2 switch I have on my network. The others are Layer 3.
If more information is needed I'll do my best to provide. Sorry if this is not explained well. Hoping someone knows what is going on and can point me to a fix. I'd rather have the caching enabled. Thanks.

**Comment by chr-lei** [comment]
I would try two things... 
1. when installing NextDNS via the script, answer N to the caching question then manually enable caching later. You can do the latter via nextdns config set -cache-size=1M ... This will leave dnsmasq active but will still have NextDNS do caching. Because of how NextDNS intercepts queries, you're unlikely to run into a double-caching scenario here.
2. you may need to set NextDNS to pass through queries to dnsmasq for the Unifi devices to work. In particular, you'll want to pass through your local domain names, reverse zones, and possibly ui.com. You can do that by adding these lines to /data/nextdns.conf and restarting:

forwarder your.domain.net.=ip.of.your.udm
forwarder 1.168.192.in-addr.arpa.=ip.of.your.udm (replace the 192, 168, 1 with the actual network subnets you're using)
forwarder ui.com.=ip.of.your.udm

I have found that allowing my local domain and the reverse zones keeps my Unifi Flex switches online, and I do run NextDNS with caching as well as dnsmasq. Hope this helps.

**Comment by linuxfrag** [comment]
> 
> 
> I would try two things...
> 
>     1. when installing NextDNS via the script, answer N to the caching question then manually enable caching later. You can do the latter via nextdns config set -cache-size=1M ... This will leave dnsmasq active but will still have NextDNS do caching. Because of how NextDNS intercepts queries, you're unlikely to run into a double-caching scenario here.
> 
>     2. you may need to set NextDNS to pass through queries to dnsmasq for the Unifi devices to work. In particular, you'll want to pass through your local domain names, reverse zones, and possibly ui.com. You can do that by adding these lines to /data/nextdns.conf and restarting:
> 
> 
> forwarder your.domain.net.=ip.of.your.udm
> forwarder 1.168.192.in-addr.arpa.=ip.of.your.udm (replace the 192, 168, 1 with the actual network subnets you're using)
> forwarder ui.com.=ip.of.your.udm
> 
> I have found that allowing my local domain and the reverse zones keeps my Unifi Flex switches online, and I do run NextDNS with caching as well as dnsmasq. Hope this helps.

So which settings would be correct for:
forwarder your.domain.net.=ip.of.your.udm

-forwarder gateway.localdomain.=192.168.1.1
or
-forwarder localdomain.=192.168.1.1

And which is correct for:
forwarder 1.168.192.in-addr.arpa.=ip.of.your.udm

-forwarder 1.168.192.in-addr.arpa.=192.168.1.1
-forwarder 2.168.192.in-addr.arpa.=192.168.1.1
or
-forwarder 1.168.192.in-addr.arpa.=192.168.1.1
-forwarder 2.168.192.in-addr.arpa.=192.168.1.2
