### ISSUE TITLE
Device name shown as Device #

### ISSUE THREAD

**Issue by svenvg93** [nextdns/nextdns#537]
**Context**
 - CLI Version:  Lastest
 - Platform:  Raspberry Pi OS
 - 
I have setup the CLI client on a Raspberry pi in router mode.
I do see all the devices names showing up expect for my iPhone (and some others which im not sure which devices they are). That one shows up as "Device 5K1DF" on the analytics page.
How can I get it to show its normal name? 

![547](https://user-images.githubusercontent.com/4511676/124127336-e56eab80-da7b-11eb-856b-db11ec4db392.jpeg)

**Comment by rs** [comment]
This is because none of the discovery methods worked for this device. What type of device is it?

When you don't run the CLI on the router, it does not have access to the DHCP lease (we will add a workaround for that), so you are only left with mDNS for discovery. You can setup the `discovery-dns` with the IP of your router to let the CLI ask your router for the reverse name of a given IP when other methods failed. This should fix most of the cases.

**Comment by svenvg93** [comment]
The client you mean? Its a iPhone 11 Pro. The router is a isp supplied, that's why I installed it on a Pi. 

Setting the discovery-dns option to the router solves it :)

**Comment by rs** [comment]
👍
