### ISSUE TITLE
deadline exceeded

### ISSUE THREAD

**Issue by deman3417** [nextdns/nextdns#579]
**Context**
deadline exceeded

 - CLI Version: 
 - 1.37.2
 - Platform: Edgeos / edgerouter x

&lt;Describe the bug>
deadline exceeded

**Comment by rs** [comment]
It means the DNS request timed out. Can be due to connectivity issue.

**Comment by deman3417** [comment]
Strange. Problem started with the upgrade from 1.36.0 to 1.37.2
Internetconnection is 24/7 alive since more than a year.

**Comment by rs** [comment]
Can you please run a https://nextdns.io/diag from the router?

**Comment by deman3417** [comment]
Today internet was completely down
Had to restart the router. 
.
Last login: Sun Sep 12 14:20:11 CEST 2021 on pts/0
Linux EdgeRouter 4.14.54-UBNT #1 SMP Tue May 11 13:23:28 UTC 2021 mips
Welcome to EdgeOS
peter@EdgeRouter:~$ sudo nextdns restart
Error: /config/scripts/post-config.d/nextdns.sh restart: exit status 1:
peter@EdgeRouter:~$ sudo nextdns stop
Error: /config/scripts/post-config.d/nextdns.sh stop: signal: killed:
peter@EdgeRouter:~$ sudo nextdns start
Error: /config/scripts/post-config.d/nextdns.sh start: signal: killed:
peter@EdgeRouter:~$ reboot now

i will do the diag when the problem reoccurs

**Comment by ralban** [comment]
I've also begun having crashes again since upgrading beyond 1.36.0. I just ran a diag and have a few log lines:

` Sep 19 07:59:22 ubnt kernel: Process 6857 (nextdns) has crashed (parent 1 (systemd) signal 10, code 2, addr 000573b4), coredumps disabled"
 Sep 19 06:21:39 ubnt nextdns[6852]: Switching endpoint: https://dns.nextdns.io#170.39.224.134,2a0e:6902:2002:12b:5054:ff:fed7:6b78"
 Sep 19 06:21:37 ubnt nextdns[6852]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::"
 Sep 19 06:21:37 ubnt nextdns[6852]: Connected 45.90.28.0:443 (con=109ms tls=252ms, TCP, TLS13)"
 Sep 19 06:21:37 ubnt nextdns[6852]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io}: exchange: roundtrip: dial tcp: looku
 Sep 19 06:21:15 ubnt nextdns[6852]: Received signal: broken pipe (ignored)"
 Sep 19 06:21:15 ubnt nextdns[6852]: Endpoint provider failed: &{dns.nextdns.io https://dns.nextdns.io#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07
 Sep 19 06:21:06 ubnt nextdns[6852]: Received signal: broken pipe (ignored)"
 Sep 19 06:20:55 ubnt nextdns[6852]: Endpoint failed: https://dns2.nextdns.io#45.90.30.0,2a07:a8c1::: roundtrip: context deadline exceeded"
 Sep 19 06:20:51 ubnt nextdns[6852]: Endpoint failed: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::: roundtrip: context deadline exceeded"`

**Comment by deman3417** [comment]
Is there a possibility to install a old version? Downgrade? 1.36.0?

**Comment by ralban** [comment]
I'm think it might be possible by using snapshot binaries of 1.36.0. I will test tomorrow, time permitting.
https://github.com/nextdns/nextdns/releases/tag/v1.36.0 is 6e203b0

And the wiki (https://snapshot.nextdns.io/master/index.html) references this command: 
`NEXTDNS_VERSION=master/SNAPSHOT-de93349 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`
I think we could substitute de93349 with 6e203b0 .

**Comment by deman3417** [comment]
It was a great idea, but ...
tried this command:
NEXTDNS_VERSION=master/SNAPSHOT-6e203b0  sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'

Anfd got this:
INFO: OS: edgeos
INFO: GOARCH: mipsle_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: master/SNAPSHOT-6e203b0
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
i) Install NextDNS
e) Exit
Choice (default=i):

**Comment by ralban** [comment]
I'm continuing to experience these errors. 

`INFO: 13:09:47 Starting NextDNS 1.37.2/linux on localhost:53
INFO: 13:09:47 Listening on TCP/127.0.0.1:53
INFO: 13:09:47 Listening on UDP/127.0.0.1:53
INFO: 13:10:08 Connected 45.90.30.0:443 (con=9ms tls=0ms, TCP, )
INFO: 13:10:11 Connected 170.39.224.134:443 (con=9ms tls=2419ms, TCP, TLS13)
INFO: 13:10:11 Switching endpoint: https://dns.nextdns.io#170.39.224.134,2a0e:6902:2002:12b:5054:ff:fed7:6b78
INFO: 13:10:11 Query 127.0.0.1 UDP A redacted[].unmsapp.com. (qry=48/res=12) 6412ms : doh resolve: context deadline exceeded
INFO: 13:10:11 Query 127.0.0.1 UDP AAAA redacted[].unmsapp.com. (qry=48/res=12) 6417ms : doh resolve: context deadline exceeded
INFO: 13:10:11 Query 127.0.0.1 UDP A redacted[].unmsapp.com. (qry=48/res=12) 6421ms : doh resolve: context deadline exceeded
INFO: 13:10:11 Query 127.0.0.1 UDP AAAA redacted[].unmsapp.com. (qry=48/res=12) 6422ms : doh resolve: context deadline exceeded`

**Comment by ralban** [comment]
Trying to.
I've reactivated the service from the CLI, but I don't think the service stays alive long enough to complete the lookup and download the diag script.
________________________________

**Comment by rs** [comment]
> Still same problem here.
> 
> Ik did run the diag a couple of times for you.

I need the ID.

**Comment by deman3417** [comment]
Ok.
How do i send it?
Not here i suppose

**Comment by rs** [comment]
You IP is not shown in the report. If not comfortable sharing publicly, please DM it to nextdns staff on help.nextdns.io.

**Comment by marcineq** [comment]
I have recently upgraded to 1.37.3 and the problems described in this issue are back after they had been fixed a couple of months ago in one the earlier releases. Also again it is accompanied by skyhigh CPU usage. Not able produce diag though as it currently doesn't work on edge routers.

**Comment by deman3417** [comment]
Already 2 months and still no solution.
Not even feedback

**Comment by deman3417** [comment]
Meanwhile I have a separate router with the nextdns cli.
It only does dns processing. 
If you enter nextdns cli in Windows as the primary dns server and a secondary "normal" dns server there is no problem.
If you enter in Windows only the nextdns cli dns router, then the problems start. 
Very strange.

**Comment by deman3417** [comment]
How do i downgrade to 1.34.4? Or do you mean 1.37.4?
1.37.4 is no solution.

**Comment by rs** [comment]
Sorry I meant 1.37.4. It's 3 days old, did you test it?

**Comment by deman3417** [comment]
Yep. Installed 1.37.4 and had the deadline problem immediately

**Comment by marcineq** [comment]
I managed to grab some output by the diag tool while "deadline exceeded" errors were produced. This is what I recorded before router stopped responding due to CPU overload:
`Testing IPv6 connectivity
  available: true
Fetching https://test.nextdns.io
  Fetch error: Get "https://test.nextdns.io": unexpected EOF
Fetching PoP name for ultra low latency primary IPv4 (ipv4.dns1.nextdns.io)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for ultra low latency secondary IPv4 (ipv4.dns2.nextdns.io)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for anycast primary IPv4 (45.90.28.0)
  zepto-waw: 9.273ms
Fetching PoP name for anycast secondary IPv4 (45.90.30.0)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for ultra low latency primary IPv6 (ipv6.dns1.nextdns.io)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for ultra low latency secondary IPv6 (ipv6.dns2.nextdns.io)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for anycast primary IPv6 (2a07:a8c0::)
Fetch error: Get "https://dns.nextdns.io/info": EOF
Fetching PoP name for anycast secondary IPv6 (2a07:a8c1::)`

**Comment by rs** [comment]
try disabling mdns with the last version (1.37.4) with `mds: disabled`. It will stop listening on multicast / 5353.

**Comment by marcineq** [comment]
> try disabling mdns with the last version (1.37.4) with `mds: disabled`. It will stop listening on multicast / 5353.

Thanks, mdns disabled. I will be verifying now if context deadling problems are retuning.

**Comment by deman3417** [comment]
Is it helpful if I give you access to my DNS server with NextDNS cli?

**Comment by marcineq** [comment]
None of my changes helped. The errors cause my router to hang couple of times a day. Fortunately I found a backup of 1.35.0 version which worked really smooth for me. So I have downgraded the CLI and we will see if the errors are gone for good...

**Comment by deman3417** [comment]
Can you share 1.35.0 and tell me how do downgrade.

**Comment by marcineq** [comment]
> Can you share 1.35.0 and tell me how do downgrade.

Here you go: https://drive.google.com/file/d/1Lf3o6mNOJRS5r2H0bU-LFxQ2TKOAziD_/view?usp=sharing
scp it to router's user home directory, stop the nextdns service, replace /config/nextdns/nextdns with the one you copied and start again.

**Comment by marcineq** [comment]
or even better - I've just found the official source:
https://github.com/nextdns/nextdns/releases/download/v1.35.0/nextdns_1.35.0_linux_mips_softfloat.tar.gz
list of releases: https://github.com/nextdns/nextdns/releases

śr., 24 lis 2021 o 21:51 deman3417 ***@***.***> napisał(a):

**Comment by vincentbernat** [comment]
Could you try with the snapshot in #618? It switches back to Go 1.16 instead of Go 1.17 which was one of the main change between 1.35 and 1.36. Comment back in #618 if it works or not. Thanks!

**Comment by andrew-susanto** [comment]
For downgrading to an older version like 1.35.0 you can use the command below
```
NEXTDNS_VERSION=1.35.0 sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
```
just change the NEXTDNS_VERSION variable to any version you want to downgrade. 

But currently, there is PR version that is in testing, this PR version is trying to solve the problem. Run below command to try the PR version.
```
NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
``` 
Make sure it shows pr-618/SNAPSHOT-9483d8b on INSTALL_RELEASE and choose upgrade 
```
ubnt@ubnt:~$ NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: edgeos
INFO: GOARCH: mipsle_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: pr-618/SNAPSHOT-9483d8b
c) Configure NextDNS
r) Remove NextDNS
e) Exit
```

**Comment by dbeusink** [comment]
Can confirm, downgrading to V1.35 resolves the problem. I will give pr-618/SNAPSHOT-9483d8b a try (#618)

**Comment by deman3417** [comment]
Joining the 9483 test

**Comment by marcineq** [comment]
and me.

**Comment by dbeusink** [comment]
Can confirm pr-618/SNAPSHOT-9483d8b #618 resolves the issue. So there is something that changed with go 1.17 that is not working correctly.

**Comment by andrew-susanto** [comment]
I agree, so far the pr-618/SNAPSHOT-9483d8b version running smoothly on my EdgeRouter. There should be something in go 1.17 that causing this issue.

**Comment by deman3417** [comment]
Second that. 9483 working smoothly.
