### ISSUE TITLE
Ability to prevent .local forwarding

### ISSUE THREAD

**Issue by spry-salt** [nextdns/nextdns#589]
**Context**
 - CLI Version: 1.37.2
 - Platform: ASUS Merlin

&lt;Describe the bug>
NextDNS CLI is running alongside dnsmasq on a router. It is configured for split horizon and works fine for my lan.

But when I try nslookup anyhost.local the NextDNS CLI is not only using mDNS to find the host name (through Bonjour?) it's also referring the query to the NextDNS servers.

Should it be doing that? Or is there a way to prevent it referring those queries upstream?

**Comment by spry-salt** [comment]
It does it for all.

**Comment by spry-salt** [comment]
Thanks. That would be a helpful privacy feature also, to avoid unnecessarily leaking mdns requests to the upstream dns.

**Comment by spry-salt** [comment]
Testing it just now, I created a rewrite for .local to 0.0.0.0. Any attempt to lookup a host with .local now gives 0.0.0.0 as you'd expect, but that may break Bonjour.

**Comment by rs** [comment]
It’s more useful with rewrites. You can add names this way.

**Comment by jsynowiec** [comment]
@rs, it looks like a recent change (circa 2022-06-06 21:20:00 UTC) to the NextDNS servers or the NextDNS block list resulted in some services failing because those services are making A and AAAA queries for `*.local` suffix, and failing to resolve such domains. For example, `ddns.synology.com.local` (one of the failing services is DDNS on Synology DSM). 

Why is NextDNS CLI forwarding such queries at all? I do not see much use in rewriting those queries using NextDNS servers. But I see it as a privacy issue – many devices like iPads, iPhones or laptops announce their name for local discovery, and those names often contain users' names or other identifiers.

How can I prevent that behavior on UDM? Keep the local suffix resolvable on the router, and do not leak it outside the network?
