### ISSUE TITLE
CLI don't auto-activate on router restart or using command-line

### ISSUE THREAD

**Issue by iJorgen** [nextdns/nextdns#609]
**Context**
 - CLI Version: 1.37.3
 - Platform: ASUS AX86U (Merlin 386.4)

After a restart of the router or using the command "nextdns restart" all DNS requests from the router isn't encrypted any more.

Now I have to manually run "nextdns activate" after each reboot or "restart" command, but would be nice if it could work automatically (as it should).

This is my config-file:

> bogus-priv true
auto-activate true
config xxxxxx
cache-size 10MB
cache-max-age 0s
max-ttl 30s
discovery-dns 
detect-captive-portals false
listen localhost:53
report-client-info true
timeout 5s
control /var/run/nextdns.sock
use-hosts true
log-queries false
hardened-privacy false
max-inflight-requests 256
setup-router true

**Comment by spry-salt** [comment]
I made a couple of modifications to my ASUS router running Merlin to deal with this:

In /jffs/scripts/services-start you should have these lines (I think nextdns already puts these in):
logger -t services-start Starting nextdns
/jffs/nextdns/nextdns.init start

In /jffs/scripts/dnsmasq.postconf add these lines to the end:
logger -t dnsmasq.postconf "Forcibly activate nextdns"
/jffs/nextdns/nextdns activate

In /jffs/scripts/service-event-end add these lines to the beginning (I did this because nextdns seems to corrupt its config file sometimes, because every time it runs it seems to rewrite that config file, don't understand why):
logger -t "service-event-end" "Fixing nextdns"
killall -9 nextdns
cp /jffs/nextdns/nextdns.conf.bak2 /jffs/nextdns/nextdns.conf
/jffs/nextdns/nextdns restart

**Comment by iJorgen** [comment]
> I made a couple of modifications to my ASUS router running Merlin to deal with this:
> 
> In /jffs/scripts/services-start you should have these lines (I think nextdns already puts these in): logger -t services-start Starting nextdns /jffs/nextdns/nextdns.init start
> 
> In /jffs/scripts/dnsmasq.postconf add these lines to the end: logger -t dnsmasq.postconf "Forcibly activate nextdns" /jffs/nextdns/nextdns activate
> 
> In /jffs/scripts/service-event-end add these lines to the beginning (I did this because nextdns seems to corrupt its config file sometimes, because every time it runs it seems to rewrite that config file, don't understand why): logger -t "service-event-end" "Fixing nextdns" killall -9 nextdns cp /jffs/nextdns/nextdns.conf.bak2 /jffs/nextdns/nextdns.conf /jffs/nextdns/nextdns restart

Thanks for your effort and workaround!! :-)  I will try it, but let's also hope the NextDNS-team addresses this issue/bug.
