### ISSUE TITLE
When will nextdns cli support QUIC?

### ISSUE THREAD

**Issue by jinkang23** [nextdns/nextdns#658]
When will QUIC be enabled for NextDNS cli?

**Comment by rs** [comment]
CLI will support HTTP/3 when a stable Go client library arises, hopefully supported by the Go team. We used to have support added using the only maintained quic library with HTTP/3 support but their client code has some serious bugs that make it unusable for us. We submitted a patch https://github.com/lucas-clemente/quic-go/pull/3157 but it wasn’t accepted. To date, no better fix as been implemented, which make me think nobody is seriously using this lib has a HTTP/3 client (it’s probably mostly used for servers).

Note that HTTP/3 support will also inflate the binary size substantially, which might impact router support. The protocol is also putting a lot of complexity in the user-land, voiding decades of transport optimizations from kernel code. On routers which often have low end CPU and low memory capacity/bandwidth, performance might be impacted.

As for DoQ, CLI relies on HTTP to carry the client info when enabled, so it is not planned to support DoQ or DoT at the moment.

**Comment by chr-lei** [comment]
@rs I am absolutely not a professional Go user/dev so excuse the ignorant question, but - is there an opportunity to fork quic-go and apply the suggested HTTP/3 fix from your PR, then roll the CLI with that fork of of quic-go? From looking at the issue on the quic-go github, it looks like there's no design for what would be considered an acceptable PR. Just thinking this might resolve the issue for NextDNS in this specific case without having to fight for the attention of quic-go.

**Comment by msoxzw** [comment]
I am also curious about how HTTP/3 is supported by NextDNS servers.

According to https://http3check.net/, [Google DNS](https://http3check.net/?host=dns.google) and [Cloudflare DNS](https://http3check.net/?host=cloudflare-dns.com) support HTTP/3, but [NextDNS](https://http3check.net/?host=doh3.dns.nextdns.io).

Moreover, what most attracts me is real 0-RTT of HTTP/3, which virtually attains latency comparable to conventional UDP. Nonetheless, the practical performance varies depending on the implementation:

"https://dns.google/dns-query" supports 0-RTT, GET and POST requests.
"https://cloudflare-dns.com/dns-query" supports 0-RTT, GET requests in order to help mitigate risk of replay attacks.
"https://doh3.dns.nextdns.io/" supports GET and POST requests.

Except for no 0-RTT, "https://doh3.dns.nextdns.io/" introduces additional delay caused by retrying with token.

**Comment by rs** [comment]
0-RTT is not yet supported. Keep in mind this additional RTT is only paid for the initial DNS request. The impact is minuscule to irrelevant for DNS.

**Comment by msoxzw** [comment]
Since connection is reused, the differences of subsequent DNS query time are nearly indistinguishable among DNS over UDP, DNS over TLS, DNS over QUIC, DNS over HTTP/2, and DNS over HTTP/3. However, considering connection establishment time, DNS over HTTP/3 with 0-RTT shines.

Furthermore, NextDNS HTTP/3 implementation is rather peculiar compared with Google DoH and Cloudflare DoH.

1. If 0-RTT is used, which is enabled by default in Firefox, connection establishment time is unexpectedly approximately 2 seconds.
2. If HTTP/3 idle timeout is set to over 30 seconds, e.g. 60 seconds, the next DNS query after 30 seconds will not be responded.
3. When connection is established, one stateless retry packet is always received, so one RTT seems to be unnecessarily added compared with Google DoH and Cloudflare DoH.

**Comment by msoxzw** [comment]
@rs, I find that https://doh3.dns.nextdns.io/ has already supported 0-RTT.

Additionally, I have collected some characteristics from several popular DNS-over-HTTP/3 providers.

NextDNS: https://doh3.dns.nextdns.io/
AdGuard: https://dns.adguard.com/dns-query
Cloudflare: https://cloudflare-dns.com/dns-query
Google: https://dns.google/dns-query

| Provider | NextDNS | AdGuard | Cloudflare | Google
| --- | --- | --- | --- | --- |
| Maximum Idle Timeout | 30 | 300 | 180 | 240
| Initial Datagram Size for IPv4 | 1252 | 1252 | 1200 | 1444
| Initial Datagram Size for IPv6 | 1232 | 1232 | 1200 | 1424
| Path MTU Discovery | yes | yes | no | yes
| 0-RTT | yes | yes | yes | yes

Unfortunately among these DoH services, NextDNS has shortest maximum idle timeout 30 seconds, but 0-RTT allow servers to negotiate low values of the connection timers without new connections latency penalties, which reduces the total number of connections that they need to manage. It is worth noting that quic://dns.nextdns.io/ has not supported 0-RTT, though HTTP/3 is built on QUIC.

**Comment by msoxzw** [comment]
@rs 
The maximum idle timeout of https://doh3.dns.nextdns.io/ and quic://dns.nextdns.io/ has been changed to 180 seconds, but quic://dns.nextdns.io/ still does not support 0-RTT and its max early data size is 0, because the TLS early_data extension in the NewSessionTicket message is defined to convey (in the max_early_data_size parameter) the amount of TLS 0-RTT data the server is willing to accept.

My aforementioned comment concerning retry packet was misleading, since I misunderstood the usage of NEW TOKEN of QUIC and misconfigured QUIC client, and consequently, NextDNS servers now do not validate address via retry packet.

The correct usage of NEW TOKEN is elaborated in [ngtcp2 README](https://github.com/ngtcp2/ngtcp2#token-not-something-included-in-retry-packet):

> Token (Not something included in Retry packet)
> ----------------------------------------------
> QUIC server might send a token to client after connection has been established. Client can send this token in subsequent connection to the server. Server verifies the token and if it succeeds, the address validation completes and lifts some restrictions on server which might speed up transfer. In order to save and/or load a token, use --token-file option of examples/client. The given file is overwritten if it already exists when storing a token.

Furthermore, The NextDNS CLI will presumably support HTTP/3 again once https://github.com/lucas-clemente/quic-go/pull/3653 is merged.

**Comment by janthony6** [comment]
just found this thread after posting one about DOH3 support for CLI. looks like this was merged...how do we enable it on the cli?

**Comment by ijuliank** [comment]
Any update? @rs

**Comment by arthsmn** [comment]
So, as the https://github.com/quic-go/quic-go/pull/3653 got closed in favor of https://github.com/quic-go/quic-go/pull/3684 are there any plans to support DOH3 now?

**Comment by rs** [comment]
I’m favouring the upcoming Go implementation. Every time I try quic-go, I find more blocking issues that have made me lose confidence in this implementation. It also inflates the binary beyond the storage capacity of some low-end routers we support, requiring the use of UPX, which comes with its own set of problems.

Again, QUIC, in the context of the CLI—mostly deployed in stable wired networks—offers no real benefits. Being a user-land implementation lacking most of the optimisations of TCP over the years, it doesn’t make it an obvious choice for routers with limited computing power and memory bandwidth.

**Comment by marten-seemann** [comment]
@rs Would love to hear what those issues are! Please feel free to open issues, or contribute PRs (as you've done before, thank you for that!). QUIC and HTTP/3 are pretty complicated protocols, and I wouldn't claim that quic-go is perfect by any means, but we've made a lot of progress and have been chewing through issues.

**Comment by rs** [comment]
@marten-seemann The last issue I found relates to the HTTP client, which seemingly does not close connections correctly before reopening new ones as I mentioned in [my last PR on your library](https://github.com/quic-go/quic-go/pull/4587). On the server side, we observe that most QUIC clients exhibit abnormal behaviour: They open connections, make a single DNS query (or sometime none), and then keep the connection open before creating new ones for subsequent queries. This prompted me to contribute the HTTP keep-alive timeout feature, so our servers aren’t vulnerable to unintentional DDoS attacks from these clients. I also suspect these clients have very poor DNS performance due to this behavior. We can’t confirm if these clients are using quic-go, but since most known DoQ and DoH3 client implementations rely on your library, I suspect they do. This leads me to believe there may be a bug in how connection reuse is implemented. I plan to create a reproducible example and report it eventually, unfortunately I haven’t had the time to do so yet.

Additionally, we have observed a clear memory leak on the server side of quic-go in our implementation. I tried to identify its source with no real success. It appears that buffers for connections are not always freed, leading to slow but certain increase of resident memory attributed to the `Connection.preSetup` function that is never released, regardless of the number of active QUIC connection. As a result, we are forced to isolate our QUIC implementation on the server to protect our service. Again, I'd need to spend more time on investigating this. 

The library size is also a significant issue for our CLI client, though I understand there isn’t much you can do about it. As you mentioned, this protocol is quite complex. I’m not convinced it provides a clear benefit in the context of this client. While DNS over QUIC or HTTP/3 can be valuable for mobile networks, the client of this repository is not deployed on such platforms. Current mobile clients (iOS and Android) aren’t prioritising their implementation either, likely for the same reasons (the protocol and its implementations are still too new). Although many people want the latest protocol versions, performance, stability, and security should not be sacrificed. These factors are more important to us than simply adopting a fancy new protocol (no offense). We will only add it when we believe it is ready and providing actual value to our users.

**Comment by marten-seemann** [comment]
Hi @rs! Thank you for your feedback, and sorry for taking a while to get back to you... but I have been busy working on exactly these problems (among others), so I have some good news to share:

In [v0.49.0](https://github.com/quic-go/quic-go/releases/tag/v0.49.0), we finally fixed the issues regarding the re-dialing of HTTP/3 connections: https://github.com/quic-go/quic-go/pull/4854, https://github.com/quic-go/quic-go/pull/4875, https://github.com/quic-go/quic-go/pull/4879. I totally understand that it's annoying that it took so long to fix this!

Regarding memory consumption, there was a memory leak that was triggered in a very obscure edge case (namely, when the QUIC connection ID was rotated just before sending out the packet containing the CONNECTION_CLOSE frame), which would lead to that connection never getting gc-ed: https://github.com/quic-go/quic-go/pull/4852. Not sure if this was the memory leak that you were running into, please let me know if you're running into anything like this again.

Speaking of memory consumption, we significantly reduced the memory allocated per session (in `preSetup`, by moving to a variable-size ring buffer instead of a fixed-size channel for received packets): https://github.com/quic-go/quic-go/pull/4928 (not included in v0.49.0, but already merged into `master`). I've seen memory usage of an app (and that's counting the memory of the entire stack, not just the QUIC stack) reduce by 60% (!) in cases where the node was handling a lot of connections.

Anyways, I realize that this is not a priority for nextdns, and that's totally fine. Just wanted to say thank you for the feedback. I really appreciate these reports, even if it sometimes takes a bit longer to resolve them.

**Comment by rs** [comment]
Thanks for the heads up @marten-seemann. We’ll test those fixes and report back.
