### ISSUE TITLE
Uninstall NextDNS CLI on UDM Pro keeps DNS routing to NextDNS

### ISSUE THREAD

**Issue by frederikrooms** [nextdns/nextdns#715]
**Context**
 - CLI Version: latest 1.37.11
 - Platform: Unifi UDM Pro console

I uninstalled NextDNS and wanted to split my DNS (Pi-Hole & NextDNS) over different networks. It seems that whatever forwarding address I added in my Unifi console, it keeps on routing to NextDNS. It know it is completely uninstalled because I lost the hostnames, but I keep getting logs from my public IP address. I deleted all the routing to NextDNS (WAN and LAN networks), but I guess it's broken somewhere. It's also impossible with Dnsmasq to push the DNS server to the DHCP clients, it keeps on forwarding to the controller where NextDNS client was installed. I tried everything, but no matter what I do, nothing changes... DHCP lease clients, new network as test,..... Though manual IP config of the clients do work :(

**Comment by embcla** [comment]
Mmmm I'm not sure I understand your issue, but some of the things you say ring a bell

I have nextdns installed on the UDMP and Pihole on a vm running somewhere else.
My networking configuration has 2 DNS servers:
1. pihole
2. localdns

This is because I'm using PiHole exclusively as configurable local dns resolver (something Ubiquiti has sadly failed to deliver even though it's fully supported by dnsmasq and the only thing they need to do is hook that up with their fancy UI).
Now it works but not well:
most dns queries from browsers to the local domains first fail, then somehow browsers reload autonomously (as if detecting network changes of some kind) and succeed in getting the right answer from PiHole (the only agent that could have the answer)

Now what you seem to be having, if I understand correctly, is a case where your PiHole is _never_ coming into play.
If so, have you tried setting it as primary dns in your global internet configuration on the UDMP (ISP configuration)?
