### ISSUE TITLE
Allow devices to use multiple configurations 

### ISSUE THREAD

**Issue by mbierman** [nextdns/nextdns#739]
One of the things I miss about pihole is that you could have a common set of rules, devices can be assigned to those rules, and you could have another set of rules that the same device could belong to at the same time. This allowed some base functionality for all devices while adding "extra" stuff for specific devices.

**Comment by rs** [comment]
Thank-you for your feedback. This repository is related to the CLI client and this feature request is about the service in general. General product ideas should be directed to our community forum https://help.nextdns.io. I'm going to close this issue here, feel free to create a new topic on our forum.

As a quick answer, your idea makes sense but we are purposely not adding such capability to keep the product experience simple. Creating different configuration is the way to apply different policies to different devices.
