### ISSUE TITLE
Synology: activate bug

### ISSUE THREAD

**Issue by grrrrreg** [nextdns/nextdns#79]
Output of a `nextdns activate` on my synology:
```
admin@jumbo:/$ nextdns activate
Error: activate: 127.0.0.1:53: no address found
```

_bug noticed live with @rs_

**Comment by grrrrreg** [comment]
FWIW install via the shell script went perfectly fine.

**Comment by rs** [comment]
11930bb24ca975d14218a4e4269f9558517b5180 might have fixed that, it will be in the 1.4.26, please try to upgrade and see if it is fixed.

**Comment by rs** [comment]
Please reopen if not fixed.

**Comment by grrrrreg** [comment]
Will do later this week, thanks for the quick turnaround !

**Comment by hansgw** [comment]
I still experience this bug with nextdns version 1.4.33

hansgw@e78:~$ sudo nextdns activate
Error: activate: 127.0.0.1:53: no address found

**Comment by ciokan** [comment]
Happens on ubiquity router as well. On a quick look I think it might be due to this line that was introduced recently: https://github.com/nextdns/nextdns/blob/11930bb24ca975d14218a4e4269f9558517b5180/activate.go#L60

I think we should have `localhost:53` there since it goes into `listenIP` after that which looks for `0.0.0.0` and `::1` then it hands it over to `addrs := hosts.LookupHost(lhost)` which fails since it receives an ip address instead of a host and it tries to map that on `hosts.byName`.

**Comment by rs** [comment]
Good catch

**Comment by charlie39** [comment]
i am still getting this error
